### ISSUE TITLE
Getting it working on AnkiDroid

### ISSUE THREAD

**Issue by mosbasik** [nihil-admirari/modern-cloze-overlapper#1]
First off - really happy your project exists!  I was running into some buggy behavior on https://github.com/michalrus/anki-simple-cloze-overlapper; by contrast your project seems to behave perfectly on those inputs.

I see in the README that this has only been tested using Anki Desktop and not AnkiDroid at this point.  I've tried it on AnkiDroid and it didn't work out of the box.  Would love to see it work on Android!

First, here's a short video demonstrating that I've successfully used Anki Desktop to generate some overlapping cloze cards with this project's card type:

[modern-cloze-overlapper-desktop-2023-04-11_14.46.45.webm](https://user-images.githubusercontent.com/5025277/231260394-be4a9d44-b761-43a3-8c65-a7b4bdae6bed.webm)

I synced my deck to AnkiWeb and from there into AnkiDroid; no special steps.  Here is what one of those cards looks like when viewed in AnkiDroid - the front is blank and the back shows only the contents of the "Back Extra" field:

[Screen_Recording_20230411_143802_AnkiDroid.webm](https://user-images.githubusercontent.com/5025277/231264282-2a492d95-5f59-444f-a8c0-4cac8aa6fec4.webm)

I checked, and `/Internal Storage/AnkiDroid/collection.media/_cloze-overlapper.mjs` does exist in the phone's file system.

You recommended making sure that the Android System WebView is up-to-date, so here's a screenshot that shows I'm running a version from 2023-03-29:

![image](https://user-images.githubusercontent.com/5025277/231262638-8c193705-3595-45aa-a029-c314e40ea171.png)

Any ideas?

**Comment by nihil-admirari** [comment]
Ok, I've got it working in an emulator. It's somewhat limited compared to Anki Desktop due to the following bugs in AnkiDroid:

- https://github.com/ankidroid/Anki-Android/issues/13819
- https://github.com/ankidroid/Anki-Android/issues/13770

I'll keep this issue opened until these bugs are resolved.

**Comment by nihil-admirari** [comment]
I was wrong about MathJax: https://github.com/ankidroid/Anki-Android/issues/13819#issuecomment-1547740342, everything already works as it should. Only nested closes and module loading on old Androids are problematic.

**Comment by nihil-admirari** [comment]
https://github.com/ankidroid/Anki-Android/pull/13899 is merged. Nested clozes apparently will have to wait until Rust backend migration.

**Comment by nihil-admirari** [comment]
https://github.com/ankidroid/Anki-Android/issues/13770 appears to be fixed in [2.17alpha5](https://github.com/ankidroid/Anki-Android/releases/tag/v2.17alpha5).
