### ISSUE TITLE
Automatic clozes for new lines

### ISSUE THREAD

**Issue by gruberjonas** [nihil-admirari/modern-cloze-overlapper#2]
Hi,

lovely JS-only solution for overlapping clozes! :)

I was wondering if it is possible to automatically (script-based) convert a multi-line text block into clozes, where each line becomes its own cloze?

Example:

A
B
C

gets converted to

{{c1::A}}
{{c2::B}}
{{c3::C}}

This would make wirting cards way more conveniet, sparing you from adding all clozes manually.

Also, if this would keep hints (A::1 letter -> {{c1:A::1 letter}}), it would be even better! :)

Excited to hear from you!

Best,
Jonas

**Comment by nihil-admirari** [comment]
Not directly: Anki backend must see `{{c1::}}` within the field. Cloze generation button can be added e.g. alongside “Reveal All” button, but you'll have to copy the generated text back to the field.

**Comment by nihil-admirari** [comment]
Done, please test.

May be I'll add support for inline hints later.

**Comment by nihil-admirari** [comment]
Added hint duplication for multi-prompt clozes.
