### ISSUE TITLE
Anki Mobile Error

### ISSUE THREAD

**Issue by AlphaStrioleno** [nihil-admirari/modern-cloze-overlapper#3]
Hi,

When I use it on Anki Mobile, I get the following error:
"ReferenceError: Can't find variable: onUpdateHook"

**Comment by nihil-admirari** [comment]
Is Anki Mobile up to date? According to https://github.com/ankitects/anki/pull/2515 `onUpdateHook` should've been made available.

**Comment by AlphaStrioleno** [comment]
Is the last version 23.10?  If so, it's on the latest version. Does that mean it's not supported yet? I need to wait for it to update.

**Comment by nihil-admirari** [comment]
Anki's author [promised hooks to become available back in May](https://github.com/ankitects/anki/pull/2515#issuecomment-1569521907):

> The next desktop release will allow you to import it from a new location, and *I will update AnkiMobile so it also works at the new location*.

Apparently they still aren't.

I've added a workaround for Anki Mobile. Please test.

**Comment by AlphaStrioleno** [comment]
Thank you for your work,
 now there is another error: TypeError: 'application/octet-stream' is not a valid JavaScript MIME type.

**Comment by nihil-admirari** [comment]
Please try once again with `.mjs` renamed to `.js`.

**Comment by AlphaStrioleno** [comment]
Thank you very much for your modification. It can now be displayed correctly on Anki Mobile.
